calendarapp/urls.py
from django.urls import path
from . import views

app_name = 'calendarapp'
urlpatterns = [
	path('', views.home, name='home'),
	# path('login', views.login, name='login'),
	# path('addevent', views.AddEventView.as_view(), name='addevent'),
    # path('netid', views.netid, name='netid'),
	#path('form', views.FormView.as_view(), name='form'),
	#path('filter', views.FilterView.as_view(), name='filter'),
	# path('addorg', views.AddOrgView.as_view(), name='addorg'),
    #path('cal', views.CalView.as_view(), name='cal'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('getOrgName/<int:orgPk>/', views.getOrgName, name='getOrgName'),
    path('getEvents', views.getEvents, name='getEvents'),
	path('getOrganizations', views.getOrganizations, name='getOrganizations'),
	path('getLocations', views.getLocations, name='getLocations'),
	path('getCategories', views.getCategories, name='getCategories'),
    path('addFavorite', views.addFavorite, name='addFavorite'),
    path('submitEvent', views.createEvent, name='submitEvent'),
    path('createOrganization', views.createOrganization, name='createOrganization'),
    path('createEvent', views.createEvent, name='createEvent'),
    # path('export', views.exportToCalendar, name='export'),
    path('addUser', views.addUser, name='addUser'),
    path('authenticateUser', views.authenticateUser, name='authenticateUser'),
    path('authenticateUser', views.authenticateUser, name='authenticateUser'),
    path('checkAdminEvent', views.checkAdminEvent, name='checkAdminEvent'),
    path('deleteEvent', views.deleteEvent, name='deleteEvent'),
    path('editEvent', views.editEvent, name='editEvent'),
    path('removeFavorite', views.removeFavorite, name='removeFavorite'),
    path('checkFavorite', views.checkFavorite, name='checkFavorite'),
    # path('isAdmin', views.isAdmin, name='isAdmin'),
    # path(r'^new$', AppointmentCreateView.as_view(), name='new_appointment'),
]

tigercal/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(r'', include('calendarapp.urls')),
]

calendarapp/models.py
# python manage.py makemigrations polls
# By running makemigrations, youre telling Django that
# youve made some changes to your models and that youd
# like the changes to be stored as a migration.

# 1) make changes here
# 2) python manage.py makemigrations
# 3) python manage.py migrate

# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from django.db import models
from django.core.exceptions import ValidationError
import arrow

# Create your models here.
class Organization(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

DEFAULT_ID = 1

class Event(models.Model):
    org = models.ForeignKey(Organization, on_delete=models.CASCADE, default=DEFAULT_ID, null=True)
    category = models.ManyToManyField(Category, default=DEFAULT_ID)
    name = models.CharField(max_length=100)
    start_datetime = models.DateTimeField(default=datetime.now)
    end_datetime = models.DateTimeField(default=datetime.now)
    location = models.CharField(max_length=200, null=True, blank=True)  # Better field type?
    is_free = models.BooleanField(default=False)
    website = models.CharField(max_length=200, null=True, blank=True)
    description = models.CharField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return self.name

    def clean(self):
        if self.start_datetime >= self.end_datetime:
            raise ValidationError('Ending times must after starting times')

class User(models.Model):
    email = models.CharField(max_length=100, default = '')
    password = models.CharField(max_length=100, default = '')
    first_name = models.CharField(max_length=100, default = '')
    last_name = models.CharField(max_length=100, default = '')
    favorite_events = models.ManyToManyField(Event, related_name = 'fav_events')
    admin = models.BooleanField(default=False)
    my_events = models.ManyToManyField(Event, related_name = 'my_events')
    my_orgs = models.ManyToManyField(Organization)

    def __str__(self):
        return self.email

class Appointment(models.Model):
    name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=15)
    time = models.DateTimeField()


    # Additional fields not visible to users
    task_id = models.CharField(max_length=50, blank=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Appointment #{0} - {1}'.format(self.pk, self.name)

    def clean(self):
        """Checks that appointments are not scheduled in the past"""

        appointment_time = arrow.get(self.time, self.time_zone.zone)

        if appointment_time < arrow.utcnow():
            raise ValidationError(
                'You cannot schedule an appointment for the past. '
                'Please check your time and time_zone')

    def schedule_reminder(self):
        """Schedule a Dramatiq task to send a reminder for this appointment"""

        # Calculate the correct time to send this reminder
        appointment_time = arrow.get(self.time)
        reminder_time = appointment_time.shift(minutes=-1440)
        now = arrow.now()
        milli_to_wait = int(
            (reminder_time - now).total_seconds()) * 1000

        # Schedule the Dramatiq task
        from .tasks import send_sms_reminder
        result = send_sms_reminder.send_with_options(
            args=(self.pk,),
            delay=milli_to_wait)

        return result.options['redis_message_id']

    def save(self, *args, **kwargs):
        """Custom save method which also schedules a reminder"""

        # Check if we have scheduled a reminder for this appointment before
        if self.task_id:
            # Revoke that task in case its time has changed
            self.cancel_task()

        # Save our appointment, which populates self.pk,
        # which is used in schedule_reminder
        super(Appointment, self).save(*args, **kwargs)

        # Schedule a new reminder task for this appointment
        self.task_id = self.schedule_reminder()

        # Save our appointment again, with the new task_id
        super(Appointment, self).save(*args, **kwargs)

calendarapp/forms.py
from django import forms
from .models import Event, Organization
from django.contrib.admin import widgets
from django.forms import ModelForm
# from datetimewidget.widgets import DateTimeWidget


class AddEventForm(ModelForm):

	class Meta:
		model = Event
		fields = ('org', 'category', 'name', 'start_datetime', 'end_datetime', 'location', 'is_free', 'website', 'description',)
		# widgets = {
  #           'start_datetime': DateTimeWidget(attrs={'id':"start_datetime"}, usel10n = True, bootstrap_version=3),
  #           'end_datetime': DateTimeWidget(attrs={'id':"end_datetime"}, usel10n = True, bootstrap_version=3)
  #           }

	def __init__(self, *args, **kwargs):
		super(AddEventForm, self).__init__(*args, **kwargs)
		#self.fields['start_datetime'].widget = widgets.AdminSplitDateTime()
		# self.fields['end_datetime'].widget = widgets.AdminSplitDateTime()

class AddOrgForm(ModelForm):

	class Meta:
		model = Organization
		fields = ('name',)

	def __init__(self, *args, **kwargs):
		super(AddOrgForm, self).__init__(*args, **kwargs)

# class FilterForm(forms.Form):
#     locations = forms.CharField()
#     is_free = forms.BooleanField()

calendarapp/views.py
#!/usr/bin/python

# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from django.views import generic
from django.urls import reverse
from django.core.serializers import serialize
from django.views.decorators.csrf import csrf_exempt
from CASClient import CASClient
from datetime import datetime
import json
import os
import CASTest
from .forms import AddEventForm, AddOrgForm
from .models import *
from dateutil.parser import parse
from django.views.generic.edit import CreateView
from django.contrib.auth.hashers import *

# Create your views here.
def home(request):

	if request.GET.get('login'):
		cas = CASClient(request)
		return cas.Authenticate()

	return render(request, 'calendarapp/home.html', {})

# Return name of organization given ID.
def getOrgName(request, orgPk):
	org = [Organization.objects.get(pk=orgPk)]
	json = serialize('json', org)
	data = {'data': json}
	return JsonResponse(data)


## THIS FILTERS THE EVENTS FOR LOCATIONS, FREE BOOLEAN, AND ORGANIZATIONS
def getEvents(request):

	locations_list = None
	categories_list = None
	org_list = None
	is_free = None
	# start_date = None
	# end_date = None
	email = None
	favorites = None

	# comma-deliminated string with list of locations
	locations = request.GET.get('locations')
	if locations and locations != "":
		locations_list = locations.split(',')
	# comma-deliminated string with list of categories
	categories = request.GET.get('categories')
	if categories and categories != "":
		categories_list = categories.split(',')
	# comma-deliminated string with list of orgs
	orgs = request.GET.get('organizations')
	if orgs and orgs != "":
		org_list = orgs.split(',')
	# should be either empty string or 'true'
	is_free = request.GET.get('is_free')
	if is_free and is_free != "":
		is_free = request.GET.get('is_free')
	# comma-deliminated string containing date (Y,M,D), i.e. '2018,12,4'
	# start_date_request = request.GET.get('start_date')
	# if start_date_request and start_date_request != "":
	# 	start_date_list = start_date_request.split(',')
	# 	if len(start_date_list) == 3:
	# 		start_date = datetime.date(start_date_list[0],
	# 									start_date_list[1], start_date_list[2])
	# # comma-deliminated string containing date (Y,M,D), i.e. '2018,12,4'
	# end_date_request = request.GET.get('end_date')
	# if (end_date_request and end_date_request != ""):
	# 	end_date_list = end_date_request.split(',')
	# 	if len(end_date_list) == 3:
	# 		end_date = datetime.date(end_date_list[0], end_date_list[1],
	# 									end_date_list[2])

	# Need to get the email of the user
	email = request.GET.get('email')

	# should be either empty string or 'true'
	favorites = request.GET.get('favorites')
	if favorites and favorites != "":
		favorites = request.GET.get('favorites')

	# event_list = filterEvents(locations_list=locations_list, categories_list=categories_list,
	# 							org_list=org_list, is_free=is_free, start_date=start_date,
	# 							end_date=end_date, email = email, favorites = favorites)

	event_list = filterEvents(locations_list=locations_list, categories_list=categories_list,
								org_list=org_list, is_free=is_free, email = email, 
								favorites = favorites)

	eventsJson = serialize('json', event_list)
	eventsDict = json.loads(eventsJson)


	for i in range(len(eventsDict)):
		# Replace org ID with org name
		org_id = eventsDict[i]['fields']['org']
		if org_id is not None:
			org_name = Organization.objects.get(id=org_id).name
			eventsDict[i]['fields']['org'] = org_name

		# Replace category ID with category name
		categories = eventsDict[i]['fields']['category']
		category_names = []
		for j in range(len(categories)):
			category_name = Category.objects.get(id=categories[j]).name
			category_names.append(category_name)
		eventsDict[i]['fields']['category'] = category_names

	eventsJson = json.dumps(eventsDict)

	data = {'Events_JSON': eventsJson}
	return JsonResponse(data)

# return list of filtered events based on parameters
# def filterEvents(locations_list=None, categories_list=None, org_list=None,
# 					is_free=None, start_date=None, end_date=None,
# 					email = None, favorites=None):

def filterEvents(locations_list=None, categories_list=None, org_list=None,
					is_free=None, email = None, favorites=None):

	event_list = Event.objects.all()

	if (favorites and favorites == "true"):
		# Find user
		user = User.objects.filter(email__exact = email)
		user = user[0]
		event_list = user.favorite_events.all()

	if (locations_list):
		event_list = event_list.filter(location__in=locations_list)
	if (categories_list):
		event_list = event_list.filter(category__name__in=categories_list)
	if (org_list):
		event_list = event_list.filter(org__name__in=org_list)
	if (is_free and is_free == "true"):
		event_list = event_list.filter(is_free__exact="True")
	# if (start_date and end_date):
	# 	event_list = event_list.filter(start_datetime__range=(start_date, end_date))

	return event_list

# return all organization names
def getOrganizations(request):
	org_names = Organization.objects.all().values_list('name', flat=True).distinct()
	org_names = [org for org in org_names if org is not None]
	return JsonResponse({'orgs':org_names})

# return all location names
def getLocations(request):
	locations = Event.objects.all().values_list('location', flat = True).distinct()
	locations = [loc for loc in locations if loc is not None]
	return JsonResponse({'locs':locations})

# return all categories
def getCategories(request):
	cat_names = Category.objects.all().values_list('name', flat = True).distinct()
	cat_names = [cat for cat in cat_names if cat is not None]
	return JsonResponse({'cats':cat_names})

# Add a user favorite
# Takes in a string (user)
# Another string (name)
# Start date and time (start_datetime)
@csrf_exempt
def addFavorite(request):

	data = json.loads(request.body.decode('utf-8'))
	params = data['params']

	email = params['email']
	name = params['name']
	start = params['start_datetime']

	start_datetime = parse(start)

	users = User.objects.filter(email__exact=email)
	user = users[0]

	events = Event.objects.filter(name__exact = name, start_datetime__exact = start_datetime)
	event = events[0]

	# Now save the designated event to their favorites
	user.favorite_events.add(event)
	return HttpResponse("Success")

# check if event is favorited
@csrf_exempt
def removeFavorite(request):

	data = json.loads(request.body.decode('utf-8'))
	params = data['params']

	email = params['email']
	name = params['name']
	start = params['start_datetime']

	start_datetime = parse(start)

	users = User.objects.filter(email__exact=email)
	user = users[0]

	events = Event.objects.filter(name__exact = name, start_datetime__exact = start_datetime)
	event = events[0]

	user.favorite_events.remove(event)
	return HttpResponse("Success")

# check if event is favorited
@csrf_exempt
def checkFavorite(request):

	data = json.loads(request.body.decode('utf-8'))
	params = data['params']

	email = params['email']
	name = params['name']
	start = params['start_datetime']

	start_datetime = parse(start)

	users = User.objects.filter(email__exact=email)
	user = users[0]

	favorite_events = user.favorite_events.all()

	events = Event.objects.filter(name__exact = name, start_datetime__exact = start_datetime)
	event = events[0]

	favorited = event in favorite_events

	if favorited == True: return HttpResponse("True")
	else: return HttpResponse("False")


@csrf_exempt
def createEvent(request):

	data = json.loads(request.body.decode('utf-8'))
	params = data['params']

	name = params['name']
	org_name = params['org']
	categories = params['cat']
	start = params['start_datetime']
	end = params['end_datetime']
	location = params['location']
	website = params['website']
	description = params['description']
	free = params['is_free']
	email = params['email']

	# Parse start and end date/times to the right format
	start_datetime = parse(start)
	end_datetime = parse(end)

	existing_events = Event.objects.filter(name__exact=name, start_datetime__exact=start_datetime)

	if (existing_events.count() > 0) :
		return HttpResponse('Duplicate event')

	# Get organizations from names
	orgs = Organization.objects.filter(name__exact=org_name)
	org = orgs[0] # Should only be one organization with that name

	# Parse category string into an array, then get the relevant category
	# objects
	cats = Category.objects.filter(name__in=categories)

	# Convert string to boolean
	print(free)
	free = str(free)
	if free == 'False': is_free = False
	elif free == 'True': is_free = True

	# Check to see if the event exists already
	# Defined by if there is an event with the same name/start time
	potential_event = Event.objects.filter(name__exact = name,
		start_datetime__exact=start_datetime)

	if potential_event.count() > 0:
		return HttpResponse('Event exists')

	e = Event(org=org, name=name, start_datetime=start_datetime, \
		end_datetime=end_datetime, is_free=is_free)
	e.save()

	e.category.set(cats) # Must set many-to-many field after the fact

	# Set non-required categories if they exist
	if location != '':
		e.location = location
	if description != '':
		e.description = description
	if website != '':
		e.website = website
	e.save()

	# Get user
	users = User.objects.filter(email__exact=email)
	user = users[0]

	user.my_events.add(e)

	return HttpResponse('Created event')

@csrf_exempt
def createOrganization(request):

	data = json.loads(request.body.decode('utf-8'))
	params = data['params']
	name = params['name']
	email = params['email']

	existing_orgs = Organization.objects.filter(name__exact=name)

	if (existing_orgs.count() == 0) :
		o = Organization(name=name)
		o.save()

		# Get user
		users = User.objects.filter(email__exact=email)
		user = users[0]

		user.my_orgs.add(o)

		return HttpResponse('Created organization')
	else:
		return HttpResponse('Duplicate organization')

calendarapp/templates/calendarapp/addevent.html
{% load static %}

<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/forms.css' %} "/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/base.css' %} "/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/global.css' %}"/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/widgets.css' %}"/>

<script type="text/javascript" 
    src="/admin/jsi18n/"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/jquery.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/jquery.init.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/actions.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/calendar.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">


    <!-- <label>Organization:</label><br>
    <select name="orgs" multiple>
      <option value="PUFSC">PUFSC</option>
      <option value="R20">R20</option>
      <option value="VTone">VTone</option>
    </select><br>

    <label>Category:</label><br>
    <select name="categories" multiple required>
      <option value="sports">Sports</option>
      <option value="music">Music</option>
      <option value="theatre">Theatre</option>
    </select><br>

    <label>Name:</label><br>
    <input type="text" name="name" required><br>

    Start (date and time):<br>
    <input type="datetime-local" name="starttime" required><br>

    End (date and time):<br>
    <input type="datetime-local" name="endttime" min="2000-01-02" required><br>

    Location:<br>
    <input type="text" name="location"><br>

    <input type="checkbox" name="free" value="free">Free?<br>

    Website:<br>
    <input type="text" name="location"><br>

    Description:<br>
    <input type="text" name="location"><br>

    <input type="submit" value="Submit"> -->

</form>

calendarapp/templates/calendarapp/addorg.html
{% load static %}

<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/forms.css' %} "/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/base.css' %} "/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/global.css' %}"/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/widgets.css' %}"/>

<script type="text/javascript" 
    src="/admin/jsi18n/"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/jquery.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/jquery.init.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/actions.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/calendar.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">

</form>

calendarapp/templates/calendarapp/detail.html
<strong>Name: </strong> {{ event.name }}<br>
<strong>Organization: </strong> {{ event.org }}<br>
{% for cat in event.category.all %}
   <strong>Category: </strong>{{ cat.name }}<br>
{% endfor %}
<strong>Start: </strong>{{ event.start_datetime }}<br>
<strong>End: </strong>{{ event.end_datetime }}<br>
<strong>Location: </strong>{{ event.location }}<br>
<strong>Website: </strong>{{ event.website }}<br>
<strong>Description: </strong>{{ event.description }}<br>

calendarapp/templates/calendarapp/event_form.html
{% extends "base.html" %}

{% load bootstrap_tags %}

{% block title %}New reminder{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">
      <div class="page-header">
        <h1>
          {% if not object.pk %}
            New appointment
          {% else %}
            Edit appointment
          {% endif %}
          </h1>
      </div>

      <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form|as_bootstrap_horizontal }}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <a href="#back" class="btn btn-default">Cancel</a>
            <button type="submit" class="btn btn-primary">
              {% if not object.pk %}
                Create appointment
              {% else %}
                Update appointment
              {% endif %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block page_css %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block page_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

  <script type="text/javascript">
      $(function() {
          $('#id_time').datetimepicker({
            format: 'MM/DD/YYYY HH:mm',
            extraFormats: ['YYYY-MM-DD HH:mm:ss'],
            sideBySide: true
          });
      });
  </script>
{% endblock %}

calendarapp/templates/calendarapp/filter.html
{% if event_list %}
    <ul>
    {% for event in event_list %}
        <a href="{% url 'calendarapp:detail' event.id %}">{{ event.name }}</a>
	<br>
    {% endfor %}
    </ul>
{% else %}
    <p>No events are available.</p>
{% endif %}

calendarapp/templates/calendarapp/form.html
<!-- <form action="filter">
  {% csrf_token %}
  Locations:<br>
  <input type="text" name="locations">
  <br>
  Free?<br>
  <input type="text" name="free">
  <br>
  Organizations:<br>
  <input type="text" name="orgs">
  <br><br>
  <input type="submit" value="Submit">
</form>  -->

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">

</form>

calendarapp/templates/calendarapp/home.html
<strong>Welcome to What's Roaring!</strong>
<br>
<form action="#" method="get">
 <input type="submit" class="btn" value="Log In" name="login">
</form>

calendarapp/templates/calendarapp/index.html
{% if event_list %}
    <ul>
    {% for event in event_list %}
        <a href="{% url 'calendarapp:detail' event.id %}">{{ event.name }}</a>
	<br>
    {% endfor %}
    </ul>
{% else %}
    <p>No events are available.</p>
{% endif %}

calendarapp/templates/calendarapp/netid.html
{{netid}}